name: "Auto Generate Next Release Semantic Version"
description: "Automatically generate next release semantic version incrementally."
author: "musyoka-morris"

branding:
  icon: "tag"
  color: "red"

inputs:
  package_root:
    description: NextSemver will look for the package.json file in in this location.
    required: false
    default: './'
  tag_prefix:
    description: By default, package.json uses semantic versioning, such as "1.0.0". A prefix can be used to add text before the tag name. For example, if tag_prefx is set to "v", then the tag would be labeled as "v1.0.0".
    required: false
  tag_suffix:
    description: Text which is applied to the end of the tag.
    required: false

outputs:
  version:
    description: 'The next semantic version generated'

runs:
  using: "node16"
  main: "index.js"
